services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manualine_frontend
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8000
    networks:
      - proxy
      - internal
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.manualine.rule=Host(`manualine.tech`)
      - traefik.http.routers.manualine.entrypoints=websecure
      - traefik.http.routers.manualine.tls.certresolver=le
      - traefik.http.services.manualine.loadbalancer.server.port=3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: manualine_backend
    networks:
      - internal
    restart: always

networks:
  proxy:
    external: true
  internal:
    driver: bridge
